Repository CMSgov/bluebutton-data-server, pull requests merged in 2019-03, with the labels that each got.

#127 BLUEBUTTON-637: Integration Tests to capture and compare endpoint output
  bluebutton-server-app/pom.xml
  bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/ClaimType.java
  bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/TransformerConstants.java
  bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/TransformerUtils.java
  bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/ServerTestUtils.java
  bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/utils/EndpointJsonResponseComparatorIT.java
  bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/utils/JsonInterceptor.java
  bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/utils/package-info.java
  bluebutton-server-app/src/test/resources/endpoint-responses/coverageRead.json
  bluebutton-server-app/src/test/resources/endpoint-responses/coverageSearchByPatientId.json
  bluebutton-server-app/src/test/resources/endpoint-responses/eobByPatientIdAll.json
  bluebutton-server-app/src/test/resources/endpoint-responses/eobByPatientIdPaged.json
  bluebutton-server-app/src/test/resources/endpoint-responses/eobReadCarrier.json
  bluebutton-server-app/src/test/resources/endpoint-responses/eobReadDme.json
  bluebutton-server-app/src/test/resources/endpoint-responses/eobReadHha.json
  bluebutton-server-app/src/test/resources/endpoint-responses/eobReadHospice.json
  bluebutton-server-app/src/test/resources/endpoint-responses/eobReadInpatient.json
  bluebutton-server-app/src/test/resources/endpoint-responses/eobReadOutpatient.json
  bluebutton-server-app/src/test/resources/endpoint-responses/eobReadPde.json
  bluebutton-server-app/src/test/resources/endpoint-responses/eobReadSnf.json
  bluebutton-server-app/src/test/resources/endpoint-responses/metadata.json
  bluebutton-server-app/src/test/resources/endpoint-responses/patientByIdentifier.json
  bluebutton-server-app/src/test/resources/endpoint-responses/patientRead.json
  bluebutton-server-app/src/test/resources/endpoint-responses/patientSearchById.json
Labels: enhancement

#130 Bluebutton 754 refactor deprecated hapi fhir code
  bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/TransformerUtils.java
  bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/AuthenticationIT.java
  bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/ServerCapabilityStatementIT.java
  bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/CoverageResourceProviderIT.java
  bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/ExplanationOfBenefitResourceProviderIT.java
  bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/PatientResourceProviderIT.java
  bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/utils/EndpointJsonResponseComparatorIT.java
Labels: enhancement

#136 BLUEBUTTON-620: Fixed IT failures caused by new record type.
  bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/ExplanationOfBenefitResourceProviderIT.java
Labels: bug

#132 BLUEBUTTON-786: Minor bugfixes and tweaks to NDC downloader
  bluebutton-server-app/pom.xml
  bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/FDADrugDataUtilityApp.java
  bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/TransformerUtils.java
Labels: bug, enhancement

#131 BLUEBUTTON-786: Initial design & implementation for SAMHSA filtering (Carrier & DME support)
  README.md
  bluebutton-server-app/pom.xml
  bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/ExplanationOfBenefitResourceProvider.java
  bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/IcdCode.java
  bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/SamhsaMatcher.java
  bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/TransformerUtils.java
  bluebutton-server-app/src/main/resources/samhsa-related-codes/README.md
  bluebutton-server-app/src/main/resources/samhsa-related-codes/codes-cpt.csv
  bluebutton-server-app/src/main/resources/samhsa-related-codes/codes-drg.csv
  bluebutton-server-app/src/main/resources/samhsa-related-codes/codes-icd-10-diagnosis.csv
  bluebutton-server-app/src/main/resources/samhsa-related-codes/codes-icd-10-procedure.csv
  bluebutton-server-app/src/main/resources/samhsa-related-codes/codes-icd-9-diagnosis.csv
  bluebutton-server-app/src/main/resources/samhsa-related-codes/codes-icd-9-procedure.csv
  bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/ServerTestUtils.java
  bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/ExplanationOfBenefitResourceProviderIT.java
  bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/SamhsaMatcherTest.java
  bluebutton-server-app/src/test/resources/endpoint-responses/metadata.json
  dev/design-samhsa-filtering.md
Labels: enhancement
